INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4088','PSYC270', 'Applied Psychology', 4528, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9538','LITE765', 'Introductory Literature', 3606, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3492','COMP801', 'Intermediate Computing', 6927, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9498','LING675', 'Advanced Linguistics', 9980, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3234','HIST523', 'Intermediate History', 7407, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7606','PSYC434', 'Introductory Psychology', 9911, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2009','LITE660', 'Applied Literature', 3851, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6294','LING377', 'Intermediate Linguistics', 8443, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8337','LING632', 'Advanced Linguistics', 1947, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9265','SOCI802', 'Introductory Sociology', 6728, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4932','LING318', 'Introductory Linguistics', 9911, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2661','LITE942', 'Intermediate Literature', 6344, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6104','PHYS250', 'Introductory Physics', 4812, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8365','PHIL405', 'Applied Philosophy', 2173, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9438','MATH568', 'Fundamentals of Mathematics', 1597, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8793','CHEM745', 'Intermediate Chemistry', 7623, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7449','MATH925', 'Fundamentals of Mathematics', 6494, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1983','ECON641', 'Advanced Economics', 5642, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9286','PHYS405', 'Applied Physics', 5169, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2673','PSYC589', 'Fundamentals of Psychology', 3630, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7242','PHYS957', 'Intermediate Physics', 4528, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2020','COMP184', 'Advanced Computing', 4050, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4818','ECON242', 'Introductory Economics', 6310, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9796','CHEM948', 'Fundamentals of Chemistry', 1056, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3483','JOUR940', 'Applied Journalism', 7604, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1316','PSYC779', 'Introductory Psychology', 7320, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7012','SOCI211', 'Fundamentals of Sociology', 9911, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9410','MATH342', 'Advanced Mathematics', 1677, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2355','LITE484', 'Advanced Literature', 6494, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9371','SOCI936', 'Advanced Sociology', 2344, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5563','LING737', 'Intermediate Linguistics', 8243, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4169','PHYS415', 'Fundamentals of Physics', 9204, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4218','PHIL781', 'Intermediate Philosophy', 8523, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6389','CHEM315', 'Advanced Chemistry', 1947, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1522','ECON674', 'Advanced Economics', 4528, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5176','JOUR958', 'Introductory Journalism', 1056, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8068','LITE210', 'Fundamentals of Literature', 7513, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6605','ECON517', 'Fundamentals of Economics', 1562, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4453','PSYC369', 'Intermediate Psychology', 7613, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7298','ACCO449', 'Fundamentals of Accounts', 2944, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4723','ECON743', 'Applied Economics', 1499, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9694','BIOL471', 'Applied Biology', 2173, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6554','SOCI856', 'Introductory Sociology', 7320, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4243','BIOL261', 'Fundamentals of Biology', 6344, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2566','PHYS677', 'Applied Physics', 7613, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6253','JOUR117', 'Intermediate Journalism', 3338, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8979','PHIL263', 'Intermediate Philosophy', 9204, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7118','MATH703', 'Intermediate Mathematics', 5314, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4861','PHYS757', 'Fundamentals of Physics', 4308, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4768','LING830', 'Intermediate Linguistics', 6344, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7137','MATH508', 'Intermediate Mathematics', 4353, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4044','PSYC671', 'Advanced Psychology', 7604, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3976','PSYC363', 'Introductory Psychology', 6728, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7596','JOUR985', 'Intermediate Journalism', 5642, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7335','PHIL102', 'Fundamentals of Philosophy', 3384, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5840','COMP622', 'Intermediate Computing', 8443, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3484','MATH608', 'Introductory Mathematics', 6942, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8854','SOCI424', 'Advanced Sociology', 6942, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6894','JOUR997', 'Advanced Journalism', 5041, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9232','ACCO545', 'Introductory Accounts', 9306, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6212','LITE633', 'Fundamentals of Literature', 8523, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9821','PSYC413', 'Fundamentals of Psychology', 1947, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3847','LING425', 'Introductory Linguistics', 6336, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5559','ACCO186', 'Intermediate Accounts', 6494, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4281','SOCI941', 'Advanced Sociology', 7313, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6373','ECON482', 'Applied Economics', 2173, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7452','PHIL395', 'Introductory Philosophy', 5169, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3375','PHYS537', 'Advanced Physics', 5041, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5713','LITE221', 'Introductory Literature', 9116, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1471','CHEM347', 'Fundamentals of Chemistry', 4089, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7233','LITE577', 'Introductory Literature', 3836, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7420','LITE737', 'Advanced Literature', 3851, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8519','LING358', 'Fundamentals of Linguistics', 2163, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5765','HIST818', 'Introductory History', 5642, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8381','BIOL318', 'Intermediate Biology', 2736, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8227','SOCI484', 'Fundamentals of Sociology', 2207, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1250','ECON737', 'Intermediate Economics', 1562, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4446','CHEM913', 'Intermediate Chemistry', 6657, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2596','COMP912', 'Introductory Computing', 1597, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2667','PSYC569', 'Intermediate Psychology', 5161, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7050','ACCO568', 'Advanced Accounts', 8355, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4330','BIOL530', 'Introductory Biology', 3384, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2107','SOCI102', 'Intermediate Sociology', 9593, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9349','JOUR319', 'Fundamentals of Journalism', 6657, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3025','SOCI925', 'Applied Sociology', 6310, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8074','ECON979', 'Applied Economics', 6502, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9695','MATH711', 'Intermediate Mathematics', 8620, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6551','PHIL343', 'Intermediate Philosophy', 2702, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7944','LITE915', 'Fundamentals of Literature', 2065, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5305','CHEM983', 'Intermediate Chemistry', 2884, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8435','SOCI513', 'Advanced Sociology', 8437, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1550','CHEM619', 'Fundamentals of Chemistry', 5642, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1214','PHYS908', 'Applied Physics', 6344, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5623','JOUR873', 'Intermediate Journalism', 2207, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6042','PSYC932', 'Introductory Psychology', 5314, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3618','ACCO171', 'Applied Accounts', 4211, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3294','PHYS285', 'Intermediate Physics', 2344, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7251','PSYC304', 'Applied Psychology', 1873, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1530','MATH826', 'Intermediate Mathematics', 4353, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1542','LING299', 'Applied Linguistics', 8443, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4303','LITE517', 'Advanced Literature', 7590, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4182','HIST139', 'Intermediate History', 3836, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3868','JOUR738', 'Advanced Journalism', 9945, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3621','LITE463', 'Introductory Literature', 4050, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5611','PSYC832', 'Fundamentals of Psychology', 1990, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6814','MATH265', 'Intermediate Mathematics', 2569, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2985','PSYC256', 'Advanced Psychology', 4349, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9052','JOUR523', 'Advanced Journalism', 2173, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2663','PSYC780', 'Intermediate Psychology', 4349, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1420','LITE643', 'Intermediate Literature', 7407, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8860','MATH206', 'Fundamentals of Mathematics', 1597, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2755','PHYS295', 'Applied Physics', 3606, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5157','BIOL840', 'Applied Biology', 4349, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1238','HIST635', 'Fundamentals of History', 6980, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3105','MATH420', 'Applied Mathematics', 9911, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9683','HIST779', 'Intermediate History', 9980, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9492','PSYC321', 'Applied Psychology', 4211, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9482','MATH641', 'Fundamentals of Mathematics', 9306, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6849','PHYS291', 'Introductory Physics', 3338, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7184','COMP738', 'Introductory Computing', 5016, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1858','HIST389', 'Applied History', 7930, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3080','PSYC753', 'Advanced Psychology', 8243, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6607','CHEM866', 'Introductory Chemistry', 5314, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2202','BIOL147', 'Fundamentals of Biology', 8243, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5610','MATH445', 'Advanced Mathematics', 1499, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1052','LING777', 'Advanced Linguistics', 6989, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3330','CHEM190', 'Applied Chemistry', 3836, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9623','LITE637', 'Applied Literature', 5192, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5743','ECON408', 'Intermediate Economics', 9980, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5019','ECON230', 'Applied Economics', 2163, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3934','HIST555', 'Fundamentals of History', 6942, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9144','BIOL636', 'Applied Biology', 3836, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3453','PHYS299', 'Applied Physics', 3851, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6335','HIST341', 'Applied History', 8620, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4565','COMP376', 'Introductory Computing', 3851, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7507','JOUR771', 'Advanced Journalism', 7930, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4146','LING684', 'Intermediate Linguistics', 7407, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4769','PSYC664', 'Advanced Psychology', 2852, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2980','PHIL195', 'Advanced Philosophy', 9911, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5789','BIOL286', 'Applied Biology', 4528, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6863','MATH359', 'Advanced Mathematics', 2207, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2697','PHYS493', 'Introductory Physics', 7313, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1397','PSYC524', 'Fundamentals of Psychology', 6927, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6394','ECON969', 'Applied Economics', 7313, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7864','BIOL361', 'Introductory Biology', 8912, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5553','PSYC286', 'Advanced Psychology', 2884, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5369','PHYS680', 'Advanced Physics', 8760, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1556','ACCO856', 'Introductory Accounts', 4089, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4623','COMP519', 'Applied Computing', 2208, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5792','BIOL125', 'Fundamentals of Biology', 9980, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6051','PSYC868', 'Fundamentals of Psychology', 7179, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9348','COMP274', 'Advanced Computing', 3851, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2833','COMP405', 'Applied Computing', 5161, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3056','COMP988', 'Fundamentals of Computing', 2944, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5974','COMP171', 'Fundamentals of Computing', 8243, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5491','SOCI370', 'Advanced Sociology', 1499, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1072','PHYS142', 'Applied Physics', 9116, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8204','PSYC622', 'Introductory Psychology', 6751, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1133','CHEM260', 'Fundamentals of Chemistry', 1607, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3070','MATH976', 'Introductory Mathematics', 5590, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5667','HIST944', 'Advanced History', 6942, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2201','BIOL306', 'Fundamentals of Biology', 5161, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1932','PHYS210', 'Intermediate Physics', 1607, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2971','PHYS330', 'Applied Physics', 6344, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3313','JOUR650', 'Introductory Journalism', 1056, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9999','LING531', 'Introductory Linguistics', 4818, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1668','SOCI934', 'Fundamentals of Sociology', 1911, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2859','PHYS869', 'Fundamentals of Physics', 8355, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6338','LITE697', 'Fundamentals of Literature', 7179, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5489','CHEM314', 'Advanced Chemistry', 8620, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4865','PHIL686', 'Introductory Philosophy', 2702, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7025','COMP595', 'Applied Computing', 7930, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6604','SOCI690', 'Intermediate Sociology', 3606, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3108','HIST265', 'Introductory History', 2065, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4004','ECON854', 'Fundamentals of Economics', 2065, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6262','LITE390', 'Intermediate Literature', 6502, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8855','LING800', 'Fundamentals of Linguistics', 2208, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4068','PSYC439', 'Applied Psychology', 7930, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5407','PHYS849', 'Fundamentals of Physics', 3307, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7413','LITE500', 'Introductory Literature', 6980, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3362','LING398', 'Advanced Linguistics', 5016, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7528','CHEM905', 'Applied Chemistry', 2065, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5930','LING203', 'Fundamentals of Linguistics', 5169, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4966','LING223', 'Fundamentals of Linguistics', 2884, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3220','LITE187', 'Introductory Literature', 6751, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4915','SOCI195', 'Applied Sociology', 2344, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6179','CHEM164', 'Intermediate Chemistry', 5868, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8665','LING579', 'Introductory Linguistics', 6728, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5033','HIST549', 'Applied History', 8443, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2252','LITE694', 'Introductory Literature', 3244, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5095','CHEM307', 'Applied Chemistry', 3338, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3047','LING876', 'Fundamentals of Linguistics', 5642, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2045','JOUR872', 'Introductory Journalism', 4050, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7613','PSYC199', 'Fundamentals of Psychology', 4349, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2133','MATH412', 'Introductory Mathematics', 3307, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4772','COMP888', 'Fundamentals of Computing', 1947, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9044','PHIL687', 'Fundamentals of Philosophy', 6310, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5272','CHEM849', 'Advanced Chemistry', 1990, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8912','COMP823', 'Advanced Computing', 1607, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3500','BIOL632', 'Applied Biology', 5314, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6306','COMP587', 'Intermediate Computing', 3559, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2599','BIOL703', 'Introductory Biology', 7320, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2072','PHYS552', 'Advanced Physics', 1873, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9264','BIOL611', 'Applied Biology', 3045, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6985','HIST974', 'Advanced History', 1121, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4992','LITE164', 'Advanced Literature', 4353, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5024','ECON657', 'Advanced Economics', 4528, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4746','HIST692', 'Applied History', 1562, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2065','BIOL510', 'Applied Biology', 4528, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7499','COMP997', 'Advanced Computing', 2208, 5);
