INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2556','PHYS955', 'Applied Physics', 7371, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6129','MATH986', 'Intermediate Mathematics', 3736, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9504','PSYC504', 'Applied Psychology', 2624, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2848','CHEM529', 'Introductory Chemistry', 5197, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2229','HIST181', 'Advanced History', 4555, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9750','ECON197', 'Advanced Economics', 3687, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3467','PSYC752', 'Applied Psychology', 5118, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9982','PSYC198', 'Applied Psychology', 9239, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2204','HIST265', 'Applied History', 2375, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4416','PHYS619', 'Introductory Physics', 3185, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8084','PSYC723', 'Advanced Psychology', 9486, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2044','LING414', 'Fundamentals of Linguistics', 1434, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5474','JOUR833', 'Advanced Journalism', 9823, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6144','JOUR709', 'Advanced Journalism', 2624, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8060','PHIL157', 'Applied Philosophy', 6759, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8408','LITE970', 'Fundamentals of Literature', 6484, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4037','LITE370', 'Intermediate Literature', 2301, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9775','PHIL248', 'Intermediate Philosophy', 3185, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3220','PHIL360', 'Introductory Philosophy', 1433, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3952','ECON691', 'Intermediate Economics', 9596, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8097','MATH850', 'Fundamentals of Mathematics', 9045, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6608','LITE452', 'Introductory Literature', 7189, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3469','JOUR438', 'Applied Journalism', 9094, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7926','ECON533', 'Intermediate Economics', 4761, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6388','ECON755', 'Fundamentals of Economics', 9974, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3843','ACCO657', 'Advanced Accounts', 5516, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7774','SOCI611', 'Fundamentals of Sociology', 6593, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7008','LITE832', 'Advanced Literature', 3185, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2759','BIOL659', 'Intermediate Biology', 5907, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2833','JOUR639', 'Fundamentals of Journalism', 2482, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8086','PSYC669', 'Fundamentals of Psychology', 5562, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7530','CHEM755', 'Intermediate Chemistry', 3687, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9532','JOUR745', 'Advanced Journalism', 6593, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5639','LING396', 'Fundamentals of Linguistics', 1432, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7762','HIST178', 'Advanced History', 2090, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7547','JOUR842', 'Advanced Journalism', 1816, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2916','SOCI661', 'Advanced Sociology', 5851, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6259','PSYC270', 'Introductory Psychology', 1788, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8583','SOCI342', 'Fundamentals of Sociology', 2375, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2980','MATH184', 'Introductory Mathematics', 5041, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1180','PHIL188', 'Applied Philosophy', 9596, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1545','HIST332', 'Applied History', 4761, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3818','LING418', 'Advanced Linguistics', 1433, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3122','ACCO507', 'Applied Accounts', 6593, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2171','JOUR551', 'Applied Journalism', 9823, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1624','HIST551', 'Introductory History', 9218, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7664','ACCO835', 'Advanced Accounts', 9193, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5319','JOUR857', 'Introductory Journalism', 3185, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5734','CHEM342', 'Introductory Chemistry', 7922, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4012','CHEM456', 'Applied Chemistry', 2090, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4701','BIOL943', 'Introductory Biology', 5108, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2327','LITE582', 'Fundamentals of Literature', 1154, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6115','MATH579', 'Introductory Mathematics', 1788, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8865','ECON316', 'Advanced Economics', 7672, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8710','JOUR161', 'Introductory Journalism', 1191, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3677','CHEM554', 'Advanced Chemistry', 2301, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1009','HIST875', 'Applied History', 1185, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5727','ECON550', 'Advanced Economics', 6593, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5233','LING490', 'Introductory Linguistics', 3736, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8596','COMP194', 'Advanced Computing', 9596, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6939','PSYC157', 'Intermediate Psychology', 8645, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4771','HIST404', 'Advanced History', 5907, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3459','LITE147', 'Introductory Literature', 4005, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8691','SOCI247', 'Fundamentals of Sociology', 2301, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2685','SOCI429', 'Introductory Sociology', 6305, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3972','CHEM206', 'Introductory Chemistry', 8645, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7491','PHYS352', 'Fundamentals of Physics', 4555, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2809','MATH438', 'Intermediate Mathematics', 3168, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3048','CHEM410', 'Intermediate Chemistry', 5976, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9025','BIOL832', 'Applied Biology', 2271, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5590','ACCO484', 'Fundamentals of Accounts', 5907, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6457','ECON194', 'Intermediate Economics', 5851, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5000','LITE839', 'Applied Literature', 5976, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2881','PSYC681', 'Intermediate Psychology', 6054, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4822','LITE146', 'Applied Literature', 7672, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1835','SOCI785', 'Applied Sociology', 6055, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7674','SOCI789', 'Fundamentals of Sociology', 3062, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6784','ACCO505', 'Introductory Accounts', 6054, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3899','COMP978', 'Advanced Computing', 7371, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1208','SOCI692', 'Introductory Sociology', 5907, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9256','JOUR451', 'Intermediate Journalism', 2482, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7097','LING327', 'Fundamentals of Linguistics', 8642, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4288','SOCI909', 'Fundamentals of Sociology', 2378, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3567','COMP249', 'Fundamentals of Computing', 8993, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3949','SOCI757', 'Applied Sociology', 9218, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4101','LITE624', 'Introductory Literature', 2482, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2473','ACCO466', 'Intermediate Accounts', 6484, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9903','HIST996', 'Intermediate History', 9823, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2429','ECON729', 'Introductory Economics', 3692, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7545','PHYS461', 'Fundamentals of Physics', 2375, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5765','CHEM153', 'Introductory Chemistry', 6484, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3526','MATH311', 'Intermediate Mathematics', 9218, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6297','MATH193', 'Introductory Mathematics', 5098, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5815','PSYC230', 'Introductory Psychology', 6768, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9158','LING131', 'Applied Linguistics', 8960, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5182','PHYS641', 'Applied Physics', 9084, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8094','ECON777', 'Fundamentals of Economics', 3687, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4952','HIST642', 'Fundamentals of History', 2829, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2537','COMP119', 'Fundamentals of Computing', 7184, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8943','HIST856', 'Intermediate History', 6593, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2722','HIST440', 'Advanced History', 8026, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4097','CHEM790', 'Introductory Chemistry', 2398, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2243','LING306', 'Intermediate Linguistics', 1432, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4414','ACCO613', 'Applied Accounts', 6768, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8318','BIOL202', 'Fundamentals of Biology', 6161, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1981','PHIL262', 'Intermediate Philosophy', 2271, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4244','PSYC611', 'Advanced Psychology', 6054, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4201','LING491', 'Advanced Linguistics', 5041, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2355','JOUR268', 'Introductory Journalism', 5197, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3188','PHYS340', 'Intermediate Physics', 5976, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3988','PSYC763', 'Intermediate Psychology', 9955, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4702','PHIL680', 'Advanced Philosophy', 3062, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2029','HIST279', 'Applied History', 6050, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6234','JOUR442', 'Applied Journalism', 2301, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6539','LITE596', 'Intermediate Literature', 2271, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3707','MATH572', 'Intermediate Mathematics', 8960, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3808','PSYC801', 'Advanced Psychology', 7184, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1190','MATH748', 'Advanced Mathematics', 5677, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2743','ACCO109', 'Introductory Accounts', 1276, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5608','LITE509', 'Fundamentals of Literature', 2375, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4055','ACCO259', 'Introductory Accounts', 8743, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3942','LING452', 'Advanced Linguistics', 1315, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8580','ACCO802', 'Advanced Accounts', 3221, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5763','PSYC312', 'Fundamentals of Psychology', 8716, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5119','CHEM693', 'Intermediate Chemistry', 5041, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4047','BIOL498', 'Fundamentals of Biology', 5562, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4126','BIOL419', 'Intermediate Biology', 9084, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5820','PSYC939', 'Intermediate Psychology', 6759, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3834','PSYC927', 'Intermediate Psychology', 8177, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9441','PSYC401', 'Applied Psychology', 8993, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2504','HIST752', 'Fundamentals of History', 6759, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4072','CHEM715', 'Advanced Chemistry', 1788, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2837','LING385', 'Fundamentals of Linguistics', 6484, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2927','PHYS159', 'Intermediate Physics', 4476, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2304','PHYS570', 'Fundamentals of Physics', 8600, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4573','MATH314', 'Fundamentals of Mathematics', 1434, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3112','SOCI334', 'Advanced Sociology', 9592, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1203','COMP398', 'Applied Computing', 1315, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8761','HIST741', 'Applied History', 2378, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9102','PHYS617', 'Introductory Physics', 9955, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4216','LITE449', 'Introductory Literature', 9592, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7846','PHYS118', 'Applied Physics', 4761, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3054','CHEM136', 'Advanced Chemistry', 9239, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5265','COMP551', 'Intermediate Computing', 6423, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3189','PHYS863', 'Applied Physics', 9955, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1619','MATH887', 'Advanced Mathematics', 6161, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1426','HIST314', 'Intermediate History', 1433, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5037','SOCI383', 'Fundamentals of Sociology', 1185, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9657','BIOL147', 'Fundamentals of Biology', 5098, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4378','MATH495', 'Intermediate Mathematics', 1154, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8349','JOUR850', 'Fundamentals of Journalism', 2829, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6096','PHIL106', 'Introductory Philosophy', 8645, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6913','PHIL131', 'Introductory Philosophy', 2375, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9769','PHIL638', 'Intermediate Philosophy', 7922, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2020','JOUR589', 'Introductory Journalism', 1191, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5167','LITE474', 'Advanced Literature', 3957, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6445','MATH213', 'Intermediate Mathematics', 4555, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7289','LING143', 'Fundamentals of Linguistics', 4071, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2352','BIOL204', 'Introductory Biology', 9592, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6675','BIOL209', 'Intermediate Biology', 3957, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6875','MATH500', 'Introductory Mathematics', 3168, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1687','JOUR300', 'Applied Journalism', 5222, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2632','LING284', 'Fundamentals of Linguistics', 2564, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9539','ECON663', 'Advanced Economics', 3021, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1444','SOCI875', 'Advanced Sociology', 8064, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3644','CHEM302', 'Applied Chemistry', 8490, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4181','LITE299', 'Introductory Literature', 9239, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5797','COMP994', 'Introductory Computing', 2482, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9062','LITE702', 'Applied Literature', 2378, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5998','PSYC678', 'Advanced Psychology', 3687, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1083','HIST334', 'Intermediate History', 1433, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6455','JOUR775', 'Applied Journalism', 3736, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9008','BIOL615', 'Introductory Biology', 4555, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5362','PHYS251', 'Intermediate Physics', 5197, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2819','MATH451', 'Advanced Mathematics', 3247, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8747','HIST855', 'Intermediate History', 6759, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2393','ECON313', 'Introductory Economics', 1019, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3058','LING310', 'Applied Linguistics', 3736, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5454','PSYC451', 'Introductory Psychology', 4476, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4619','PSYC712', 'Intermediate Psychology', 1788, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7753','PHYS759', 'Intermediate Physics', 4761, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5330','LITE320', 'Intermediate Literature', 3168, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9536','PSYC339', 'Introductory Psychology', 9324, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2511','MATH413', 'Intermediate Mathematics', 9045, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6789','COMP278', 'Intermediate Computing', 1875, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1140','BIOL886', 'Introductory Biology', 9486, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1414','CHEM140', 'Introductory Chemistry', 3221, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9050','PHYS205', 'Applied Physics', 1433, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8064','MATH957', 'Introductory Mathematics', 6832, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1727','LING279', 'Applied Linguistics', 2829, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('8687','MATH484', 'Introductory Mathematics', 2980, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5769','PHYS497', 'Intermediate Physics', 2301, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3371','ACCO335', 'Applied Accounts', 8600, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2013','PHIL700', 'Fundamentals of Philosophy', 5108, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5145','ECON827', 'Fundamentals of Economics', 9218, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4291','ECON501', 'Applied Economics', 8177, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9535','MATH729', 'Introductory Mathematics', 3692, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7812','HIST737', 'Intermediate History', 3221, 2);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('5711','LING165', 'Fundamentals of Linguistics', 6423, 4);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9488','LITE858', 'Fundamentals of Literature', 7371, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7368','LITE159', 'Advanced Literature', 5329, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6120','LING142', 'Introductory Linguistics', 8645, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('4786','SOCI179', 'Intermediate Sociology', 8064, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('3479','HIST493', 'Applied History', 9193, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('9710','PHIL349', 'Intermediate Philosophy', 2482, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('6101','ECON485', 'Intermediate Economics', 9059, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7559','COMP384', 'Applied Computing', 5851, 5);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('7433','HIST853', 'Intermediate History', 6484, 3);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('1684','SOCI397', 'Intermediate Sociology', 2378, 1);
INSERT INTO Course (course_id, course_code, course_name, lecturerID, created_by) VALUES ('2238','JOUR783', 'Fundamentals of Journalism', 8600, 4);
