use cms;

INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6173, 'PHYS959', 'Advanced Physics', 1, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2017, 'JOUR457', 'Advanced Journalism', 95, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2593, 'SOCI110', 'Advanced Sociology', 79, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9191, 'PSYC684', 'Fundamentals of Psychology', 19, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2351, 'COMP851', 'Advanced Computing', 46, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6595, 'MATH207', 'Intro Mathematics', 41, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3232, 'LING323', 'Fundamentals of Linguistics', 20, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4794, 'PHIL598', 'Advanced Philosophy', 24, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6627, 'ACCO194', 'Fundamentals of Accounts', 97, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6109, 'ACCO997', 'Advanced Accounts', 21, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7501, 'JOUR167', 'Intro Journalism', 94, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6262, 'PSYC584', 'Advanced Psychology', 29, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1126, 'JOUR190', 'Advanced Journalism', 20, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5825, 'ACCO992', 'Intro Accounts', 65, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4647, 'MATH763', 'Fundamentals of Mathematics', 33, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3155, 'COMP468', 'Intro Computing', 93, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9326, 'BIOL248', 'Intro Biology', 90, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4769, 'BIOL513', 'Intro Biology', 68, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6604, 'PSYC607', 'Intro Psychology', 53, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3420, 'MATH863', 'Fundamentals of Mathematics', 2, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9564, 'PHIL192', 'Advanced Philosophy', 11, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4025, 'ECON659', 'Intro Economics', 73, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7539, 'COMP563', 'Advanced Computing', 31, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5997, 'CHEM853', 'Intro Chemistry', 71, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5258, 'ECON680', 'Advanced Economics', 62, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7159, 'MATH306', 'Advanced Mathematics', 1, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8617, 'LITE752', 'Advanced Literature', 31, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3148, 'MATH841', 'Advanced Mathematics', 77, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9927, 'SOCI928', 'Advanced Sociology', 55, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1036, 'PSYC225', 'Advanced Psychology', 50, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2906, 'PHIL823', 'Fundamentals of Philosophy', 35, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8333, 'MATH600', 'Fundamentals of Mathematics', 29, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9246, 'ACCO490', 'Advanced Accounts', 20, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3673, 'COMP268', 'Fundamentals of Computing', 96, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4766, 'MATH305', 'Fundamentals of Mathematics', 93, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2837, 'MATH532', 'Fundamentals of Mathematics', 22, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1344, 'ACCO789', 'Intro Accounts', 13, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7395, 'COMP458', 'Advanced Computing', 97, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5794, 'LITE215', 'Advanced Literature', 64, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1721, 'LING873', 'Fundamentals of Linguistics', 24, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4436, 'LING401', 'Fundamentals of Linguistics', 35, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5070, 'PHIL360', 'Fundamentals of Philosophy', 14, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4133, 'SOCI495', 'Fundamentals of Sociology', 52, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3877, 'SOCI171', 'Fundamentals of Sociology', 6, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3220, 'MATH651', 'Advanced Mathematics', 95, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3275, 'LING786', 'Fundamentals of Linguistics', 68, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4367, 'CHEM159', 'Fundamentals of Chemistry', 70, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7669, 'ACCO120', 'Advanced Accounts', 78, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4814, 'MATH851', 'Intro Mathematics', 61, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1677, 'JOUR393', 'Intro Journalism', 37, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2014, 'PSYC372', 'Advanced Psychology', 97, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8365, 'LITE610', 'Advanced Literature', 72, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4089, 'BIOL767', 'Fundamentals of Biology', 21, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6752, 'ACCO587', 'Intro Accounts', 37, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6180, 'PHIL710', 'Fundamentals of Philosophy', 73, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7548, 'SOCI280', 'Fundamentals of Sociology', 40, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9180, 'MATH776', 'Fundamentals of Mathematics', 92, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9962, 'HIST768', 'Fundamentals of History', 22, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9418, 'SOCI444', 'Intro Sociology', 28, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5033, 'BIOL391', 'Intro Biology', 41, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8015, 'MATH231', 'Advanced Mathematics', 34, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2266, 'PSYC442', 'Fundamentals of Psychology', 75, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5047, 'CHEM221', 'Advanced Chemistry', 47, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5230, 'PSYC712', 'Fundamentals of Psychology', 37, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9061, 'LING686', 'Advanced Linguistics', 25, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8231, 'PHYS476', 'Fundamentals of Physics', 6, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5052, 'LING731', 'Fundamentals of Linguistics', 89, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4911, 'PSYC878', 'Fundamentals of Psychology', 13, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4032, 'SOCI853', 'Intro Sociology', 30, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5243, 'PSYC404', 'Intro Psychology', 90, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4139, 'PHYS727', 'Intro Physics', 62, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3442, 'PHYS940', 'Intro Physics', 41, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3386, 'LING945', 'Fundamentals of Linguistics', 15, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5198, 'JOUR234', 'Fundamentals of Journalism', 10, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1060, 'MATH763', 'Advanced Mathematics', 64, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2440, 'SOCI350', 'Advanced Sociology', 1, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2311, 'CHEM989', 'Intro Chemistry', 15, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3635, 'ECON647', 'Fundamentals of Economics', 42, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6140, 'PHYS978', 'Advanced Physics', 63, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9735, 'HIST819', 'Intro History', 86, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8020, 'PHIL467', 'Intro Philosophy', 96, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5058, 'PSYC767', 'Intro Psychology', 49, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7881, 'SOCI141', 'Advanced Sociology', 3, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4414, 'PHYS126', 'Fundamentals of Physics', 20, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7477, 'LING183', 'Advanced Linguistics', 84, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9191, 'SOCI582', 'Fundamentals of Sociology', 43, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4529, 'MATH891', 'Intro Mathematics', 97, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1370, 'MATH611', 'Intro Mathematics', 27, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1804, 'CHEM935', 'Intro Chemistry', 20, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8018, 'COMP256', 'Advanced Computing', 4, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6546, 'PSYC363', 'Fundamentals of Psychology', 17, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8205, 'CHEM843', 'Advanced Chemistry', 37, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9160, 'PSYC170', 'Fundamentals of Psychology', 75, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1391, 'JOUR392', 'Intro Journalism', 37, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1012, 'HIST204', 'Advanced History', 62, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6709, 'LITE310', 'Intro Literature', 38, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6043, 'CHEM247', 'Fundamentals of Chemistry', 52, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7156, 'SOCI459', 'Intro Sociology', 54, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7113, 'PSYC217', 'Intro Psychology', 26, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6179, 'LITE739', 'Intro Literature', 98, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1330, 'PHIL244', 'Advanced Philosophy', 97, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6673, 'LITE141', 'Advanced Literature', 86, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9271, 'LITE727', 'Fundamentals of Literature', 39, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6494, 'CHEM391', 'Intro Chemistry', 13, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9410, 'PHIL685', 'Fundamentals of Philosophy', 83, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9221, 'LITE871', 'Intro Literature', 51, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8948, 'PSYC438', 'Fundamentals of Psychology', 22, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4925, 'ECON486', 'Fundamentals of Economics', 86, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2830, 'HIST381', 'Intro History', 24, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5432, 'PHYS661', 'Fundamentals of Physics', 50, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2118, 'COMP923', 'Fundamentals of Computing', 73, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7814, 'MATH888', 'Advanced Mathematics', 56, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3614, 'CHEM446', 'Advanced Chemistry', 51, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5205, 'CHEM697', 'Fundamentals of Chemistry', 23, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3860, 'HIST769', 'Intro History', 28, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8775, 'MATH928', 'Intro Mathematics', 26, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5922, 'JOUR258', 'Fundamentals of Journalism', 8, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6103, 'ACCO111', 'Advanced Accounts', 5, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1301, 'MATH614', 'Intro Mathematics', 8, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5374, 'HIST439', 'Advanced History', 96, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7836, 'LING755', 'Advanced Linguistics', 26, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9080, 'BIOL219', 'Advanced Biology', 93, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6854, 'PSYC316', 'Intro Psychology', 82, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1107, 'HIST536', 'Intro History', 76, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1375, 'LITE952', 'Fundamentals of Literature', 25, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7487, 'CHEM807', 'Advanced Chemistry', 38, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9315, 'ECON246', 'Advanced Economics', 34, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3807, 'LING281', 'Intro Linguistics', 38, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4504, 'COMP256', 'Fundamentals of Computing', 29, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2810, 'PHIL134', 'Advanced Philosophy', 31, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8277, 'PHYS559', 'Advanced Physics', 60, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9049, 'HIST240', 'Fundamentals of History', 5, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6025, 'BIOL830', 'Advanced Biology', 44, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1941, 'JOUR509', 'Fundamentals of Journalism', 43, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2384, 'PHIL999', 'Fundamentals of Philosophy', 36, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8307, 'PHIL244', 'Advanced Philosophy', 79, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7811, 'JOUR752', 'Advanced Journalism', 80, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6116, 'SOCI639', 'Intro Sociology', 71, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5906, 'ACCO750', 'Intro Accounts', 89, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4721, 'LITE944', 'Intro Literature', 16, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9501, 'JOUR105', 'Fundamentals of Journalism', 61, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7513, 'LITE672', 'Intro Literature', 56, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4196, 'PHIL742', 'Fundamentals of Philosophy', 48, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1236, 'MATH145', 'Advanced Mathematics', 57, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4666, 'PSYC875', 'Fundamentals of Psychology', 79, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2650, 'HIST290', 'Fundamentals of History', 79, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5162, 'JOUR803', 'Advanced Journalism', 90, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1265, 'MATH393', 'Advanced Mathematics', 99, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4692, 'LING590', 'Fundamentals of Linguistics', 52, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6737, 'ACCO759', 'Advanced Accounts', 66, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9470, 'PHIL849', 'Fundamentals of Philosophy', 27, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1858, 'CHEM250', 'Advanced Chemistry', 84, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9713, 'ACCO624', 'Intro Accounts', 87, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1399, 'ECON503', 'Intro Economics', 86, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8525, 'HIST526', 'Intro History', 77, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7714, 'LING710', 'Advanced Linguistics', 67, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4528, 'ECON158', 'Advanced Economics', 27, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1307, 'PHIL714', 'Intro Philosophy', 69, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5274, 'PHYS480', 'Advanced Physics', 35, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8127, 'HIST837', 'Fundamentals of History', 73, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2963, 'LITE395', 'Intro Literature', 9, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3330, 'COMP675', 'Intro Computing', 30, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3732, 'BIOL670', 'Intro Biology', 99, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5707, 'MATH867', 'Fundamentals of Mathematics', 35, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8745, 'LING301', 'Intro Linguistics', 38, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6153, 'PSYC774', 'Advanced Psychology', 42, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3036, 'JOUR374', 'Fundamentals of Journalism', 47, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9974, 'HIST133', 'Advanced History', 12, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2114, 'BIOL908', 'Intro Biology', 15, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2550, 'PHIL490', 'Fundamentals of Philosophy', 95, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7907, 'LITE945', 'Fundamentals of Literature', 90, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9375, 'COMP614', 'Intro Computing', 53, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9202, 'MATH234', 'Intro Mathematics', 66, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7957, 'PSYC500', 'Fundamentals of Psychology', 53, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3442, 'BIOL750', 'Intro Biology', 50, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2898, 'PHYS815', 'Intro Physics', 96, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9383, 'MATH863', 'Advanced Mathematics', 13, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3341, 'SOCI889', 'Advanced Sociology', 48, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8798, 'PSYC239', 'Fundamentals of Psychology', 34, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4314, 'LITE666', 'Advanced Literature', 48, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8077, 'PSYC397', 'Fundamentals of Psychology', 99, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5687, 'PHYS426', 'Intro Physics', 9, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8859, 'COMP199', 'Advanced Computing', 98, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8193, 'LING914', 'Intro Linguistics', 68, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6839, 'PHYS460', 'Intro Physics', 91, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3545, 'SOCI767', 'Fundamentals of Sociology', 38, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6050, 'CHEM911', 'Intro Chemistry', 65, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9857, 'ECON418', 'Advanced Economics', 73, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4129, 'LING876', 'Fundamentals of Linguistics', 58, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6681, 'ECON360', 'Fundamentals of Economics', 41, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4127, 'ECON192', 'Advanced Economics', 83, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9678, 'BIOL604', 'Intro Biology', 4, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4033, 'CHEM687', 'Advanced Chemistry', 66, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2896, 'HIST501', 'Intro History', 79, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2764, 'PHYS578', 'Intro Physics', 85, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6135, 'PHYS998', 'Advanced Physics', 69, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6139, 'PHIL289', 'Advanced Philosophy', 80, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1142, 'PHIL293', 'Intro Philosophy', 15, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6053, 'MATH451', 'Fundamentals of Mathematics', 7, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1754, 'MATH337', 'Advanced Mathematics', 84, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9288, 'ECON638', 'Advanced Economics', 81, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1659, 'HIST738', 'Intro History', 95, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7507, 'SOCI170', 'Intro Sociology', 19, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1263, 'PHIL478', 'Advanced Philosophy', 35, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5901, 'SOCI526', 'Advanced Sociology', 33, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6811, 'COMP828', 'Advanced Computing', 3, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3286, 'HIST571', 'Intro History', 29, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5650, 'MATH368', 'Intro Mathematics', 100, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4489, 'LITE770', 'Fundamentals of Literature', 19, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4806, 'ECON406', 'Fundamentals of Economics', 62, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8784, 'LING154', 'Fundamentals of Linguistics', 61, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7408, 'PHIL693', 'Advanced Philosophy', 67, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6518, 'SOCI623', 'Fundamentals of Sociology', 77, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4508, 'PHYS542', 'Fundamentals of Physics', 76, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8702, 'CHEM793', 'Advanced Chemistry', 23, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9582, 'BIOL872', 'Advanced Biology', 51, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3841, 'PHIL738', 'Intro Philosophy', 80, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8725, 'CHEM866', 'Advanced Chemistry', 48, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8156, 'LING264', 'Advanced Linguistics', 63, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9574, 'LING943', 'Intro Linguistics', 3, 5);