INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4168, 'PSYC362', 'Fundamentals of Psychology', 83, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5651, 'MATH263', 'Fundamentals of Mathematics', 39, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8735, 'ACCO900', 'Intro Accounts', 74, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3862, 'PHYS267', 'Advanced Physics', 82, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3969, 'ACCO822', 'Advanced Accounts', 61, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6556, 'ACCO464', 'Advanced Accounts', 74, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4944, 'PHYS932', 'Intro Physics', 71, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4943, 'PHIL244', 'Advanced Philosophy', 20, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9702, 'BIOL208', 'Fundamentals of Biology', 25, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8345, 'JOUR973', 'Advanced Journalism', 44, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7267, 'LITE519', 'Fundamentals of Literature', 40, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2450, 'LING329', 'Advanced Linguistics', 48, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9026, 'MATH261', 'Fundamentals of Mathematics', 81, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4803, 'BIOL812', 'Fundamentals of Biology', 59, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3354, 'ECON210', 'Intro Economics', 43, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6252, 'COMP992', 'Fundamentals of Computing', 72, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2315, 'HIST512', 'Advanced History', 49, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7305, 'SOCI421', 'Fundamentals of Sociology', 82, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9174, 'ECON978', 'Advanced Economics', 17, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9171, 'JOUR217', 'Intro Journalism', 36, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8224, 'PSYC105', 'Intro Psychology', 52, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5625, 'ECON713', 'Fundamentals of Economics', 12, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7503, 'LITE425', 'Advanced Literature', 49, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7507, 'HIST331', 'Fundamentals of History', 28, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4115, 'COMP190', 'Advanced Computing', 9, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3546, 'ECON432', 'Intro Economics', 19, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6009, 'PHYS341', 'Advanced Physics', 58, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2855, 'ACCO764', 'Intro Accounts', 2, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1115, 'SOCI943', 'Intro Sociology', 79, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4827, 'PHIL801', 'Advanced Philosophy', 98, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1064, 'SOCI189', 'Fundamentals of Sociology', 72, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4650, 'HIST720', 'Fundamentals of History', 46, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5914, 'SOCI699', 'Advanced Sociology', 2, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1158, 'JOUR567', 'Advanced Journalism', 17, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6797, 'PHYS376', 'Advanced Physics', 3, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2190, 'LITE255', 'Intro Literature', 95, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2427, 'CHEM160', 'Intro Chemistry', 86, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8813, 'HIST175', 'Intro History', 14, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9837, 'COMP711', 'Advanced Computing', 71, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9716, 'BIOL844', 'Advanced Biology', 55, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6011, 'MATH538', 'Intro Mathematics', 52, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5879, 'LING236', 'Intro Linguistics', 32, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6185, 'MATH418', 'Intro Mathematics', 61, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4398, 'LING530', 'Advanced Linguistics', 53, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8791, 'CHEM982', 'Fundamentals of Chemistry', 56, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5296, 'HIST837', 'Fundamentals of History', 72, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8031, 'LING914', 'Intro Linguistics', 78, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7164, 'ACCO277', 'Advanced Accounts', 60, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8642, 'MATH128', 'Intro Mathematics', 63, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7377, 'LITE688', 'Fundamentals of Literature', 2, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2048, 'JOUR140', 'Intro Journalism', 31, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4540, 'BIOL231', 'Advanced Biology', 54, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9522, 'JOUR879', 'Advanced Journalism', 76, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2019, 'COMP220', 'Advanced Computing', 88, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3846, 'COMP527', 'Advanced Computing', 9, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3291, 'JOUR774', 'Advanced Journalism', 31, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2836, 'ECON472', 'Advanced Economics', 64, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6734, 'PHYS314', 'Intro Physics', 35, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7477, 'BIOL106', 'Intro Biology', 88, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1748, 'ACCO536', 'Intro Accounts', 74, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9689, 'MATH728', 'Intro Mathematics', 49, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6680, 'ECON722', 'Intro Economics', 59, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9654, 'LITE613', 'Advanced Literature', 59, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5183, 'MATH444', 'Intro Mathematics', 37, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7422, 'LING441', 'Advanced Linguistics', 59, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5683, 'PHYS720', 'Intro Physics', 26, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3845, 'HIST706', 'Fundamentals of History', 57, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1749, 'MATH357', 'Intro Mathematics', 24, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3152, 'ACCO811', 'Fundamentals of Accounts', 81, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2769, 'LING447', 'Intro Linguistics', 9, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1312, 'CHEM154', 'Fundamentals of Chemistry', 11, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1909, 'HIST114', 'Fundamentals of History', 96, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8658, 'PHIL249', 'Intro Philosophy', 32, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3292, 'HIST657', 'Intro History', 74, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8060, 'LING669', 'Fundamentals of Linguistics', 80, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1416, 'LITE367', 'Advanced Literature', 43, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3773, 'LITE100', 'Intro Literature', 45, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8277, 'LING359', 'Fundamentals of Linguistics', 69, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3392, 'PHIL195', 'Intro Philosophy', 2, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6083, 'ECON794', 'Fundamentals of Economics', 42, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4494, 'ACCO519', 'Advanced Accounts', 13, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6716, 'LING406', 'Intro Linguistics', 9, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6723, 'PHIL640', 'Intro Philosophy', 10, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3610, 'LITE108', 'Fundamentals of Literature', 56, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3374, 'PHYS433', 'Intro Physics', 82, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8436, 'LITE697', 'Fundamentals of Literature', 73, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6269, 'PHIL863', 'Intro Philosophy', 63, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8058, 'HIST666', 'Advanced History', 88, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5609, 'BIOL787', 'Intro Biology', 76, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9989, 'PSYC370', 'Fundamentals of Psychology', 60, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6521, 'CHEM588', 'Intro Chemistry', 45, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4745, 'SOCI974', 'Advanced Sociology', 77, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9840, 'JOUR438', 'Advanced Journalism', 24, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3366, 'JOUR683', 'Intro Journalism', 31, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4825, 'JOUR175', 'Advanced Journalism', 86, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3820, 'COMP355', 'Fundamentals of Computing', 9, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5586, 'COMP182', 'Fundamentals of Computing', 31, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4649, 'MATH774', 'Advanced Mathematics', 64, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9645, 'LITE635', 'Fundamentals of Literature', 26, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2470, 'MATH449', 'Advanced Mathematics', 5, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4891, 'PHYS563', 'Advanced Physics', 29, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2019, 'COMP212', 'Intro Computing', 74, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8070, 'LING759', 'Advanced Linguistics', 63, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4612, 'LING193', 'Fundamentals of Linguistics', 7, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5678, 'LING883', 'Advanced Linguistics', 100, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3873, 'BIOL685', 'Fundamentals of Biology', 22, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1880, 'PHYS187', 'Fundamentals of Physics', 64, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7975, 'PHYS766', 'Advanced Physics', 66, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7551, 'BIOL402', 'Intro Biology', 92, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8404, 'JOUR609', 'Intro Journalism', 39, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2546, 'COMP309', 'Intro Computing', 16, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9017, 'PHYS184', 'Intro Physics', 26, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9995, 'SOCI694', 'Fundamentals of Sociology', 84, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6002, 'LITE735', 'Intro Literature', 3, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7207, 'COMP147', 'Advanced Computing', 77, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6543, 'ECON292', 'Fundamentals of Economics', 98, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1288, 'HIST243', 'Intro History', 47, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1791, 'CHEM803', 'Intro Chemistry', 37, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3809, 'LING378', 'Fundamentals of Linguistics', 3, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5738, 'PHYS518', 'Advanced Physics', 24, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4120, 'COMP993', 'Fundamentals of Computing', 27, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6552, 'SOCI669', 'Fundamentals of Sociology', 22, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1975, 'ACCO101', 'Intro Accounts', 59, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2954, 'PSYC816', 'Advanced Psychology', 73, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7826, 'CHEM756', 'Intro Chemistry', 71, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8237, 'BIOL430', 'Fundamentals of Biology', 39, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6483, 'PSYC331', 'Advanced Psychology', 94, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9365, 'LITE257', 'Fundamentals of Literature', 12, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4539, 'SOCI516', 'Fundamentals of Sociology', 22, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6163, 'SOCI419', 'Fundamentals of Sociology', 75, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2375, 'MATH859', 'Advanced Mathematics', 21, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5306, 'CHEM304', 'Fundamentals of Chemistry', 36, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4649, 'BIOL963', 'Fundamentals of Biology', 1, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6332, 'PHIL334', 'Intro Philosophy', 24, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5675, 'PHYS713', 'Intro Physics', 89, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8760, 'JOUR549', 'Fundamentals of Journalism', 61, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4723, 'ECON809', 'Fundamentals of Economics', 80, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3212, 'SOCI128', 'Advanced Sociology', 79, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1146, 'PSYC245', 'Intro Psychology', 46, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9217, 'ECON748', 'Fundamentals of Economics', 15, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2297, 'ACCO311', 'Fundamentals of Accounts', 76, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2929, 'ACCO650', 'Intro Accounts', 16, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8967, 'PSYC143', 'Fundamentals of Psychology', 96, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3913, 'ECON251', 'Intro Economics', 86, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1926, 'PHYS595', 'Fundamentals of Physics', 83, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8994, 'ACCO247', 'Intro Accounts', 6, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3892, 'PHYS706', 'Fundamentals of Physics', 28, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3624, 'HIST859', 'Advanced History', 25, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2047, 'BIOL134', 'Fundamentals of Biology', 93, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1625, 'ECON836', 'Intro Economics', 37, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5467, 'MATH349', 'Fundamentals of Mathematics', 63, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2729, 'PHYS501', 'Intro Physics', 95, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5656, 'ECON505', 'Fundamentals of Economics', 58, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5951, 'JOUR425', 'Fundamentals of Journalism', 46, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1638, 'HIST332', 'Advanced History', 56, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2938, 'LING364', 'Fundamentals of Linguistics', 87, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7815, 'COMP197', 'Fundamentals of Computing', 50, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5938, 'LITE469', 'Advanced Literature', 38, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2874, 'MATH413', 'Fundamentals of Mathematics', 68, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7369, 'ECON987', 'Intro Economics', 75, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6559, 'COMP533', 'Intro Computing', 35, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1342, 'PHYS108', 'Advanced Physics', 79, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3645, 'LITE608', 'Intro Literature', 65, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2877, 'CHEM691', 'Advanced Chemistry', 54, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6025, 'SOCI510', 'Fundamentals of Sociology', 42, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5938, 'MATH768', 'Intro Mathematics', 35, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6336, 'PHIL614', 'Advanced Philosophy', 14, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2920, 'ECON342', 'Fundamentals of Economics', 34, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7921, 'PSYC900', 'Fundamentals of Psychology', 30, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2902, 'JOUR793', 'Fundamentals of Journalism', 20, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4092, 'COMP704', 'Fundamentals of Computing', 83, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4504, 'PHIL537', 'Intro Philosophy', 28, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7890, 'COMP814', 'Advanced Computing', 56, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1648, 'COMP549', 'Fundamentals of Computing', 49, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9411, 'PHYS669', 'Advanced Physics', 29, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4824, 'LITE505', 'Advanced Literature', 34, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8002, 'ACCO648', 'Intro Accounts', 21, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7796, 'ECON661', 'Advanced Economics', 31, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2526, 'LING127', 'Fundamentals of Linguistics', 55, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8113, 'COMP987', 'Advanced Computing', 97, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6113, 'JOUR376', 'Fundamentals of Journalism', 6, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7528, 'PHYS156', 'Intro Physics', 33, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6269, 'PHIL312', 'Advanced Philosophy', 52, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4726, 'PHYS999', 'Fundamentals of Physics', 83, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2361, 'SOCI775', 'Advanced Sociology', 65, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7390, 'LITE925', 'Intro Literature', 17, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8844, 'MATH129', 'Advanced Mathematics', 81, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2586, 'CHEM682', 'Advanced Chemistry', 77, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1523, 'COMP713', 'Advanced Computing', 55, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5916, 'LITE535', 'Advanced Literature', 100, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5054, 'LITE334', 'Intro Literature', 56, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8128, 'ACCO165', 'Advanced Accounts', 55, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5887, 'CHEM813', 'Advanced Chemistry', 62, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9470, 'COMP323', 'Advanced Computing', 14, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6699, 'ACCO278', 'Intro Accounts', 67, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4247, 'JOUR670', 'Fundamentals of Journalism', 3, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9743, 'HIST993', 'Intro History', 12, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1989, 'PSYC177', 'Intro Psychology', 1, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (6374, 'PHYS462', 'Intro Physics', 14, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8122, 'LING439', 'Advanced Linguistics', 92, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3770, 'PHYS237', 'Advanced Physics', 80, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3208, 'PHIL567', 'Intro Philosophy', 85, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (4298, 'SOCI745', 'Fundamentals of Sociology', 70, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8166, 'CHEM541', 'Fundamentals of Chemistry', 71, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5741, 'HIST274', 'Advanced History', 34, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5112, 'ACCO362', 'Intro Accounts', 24, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (3391, 'PSYC299', 'Intro Psychology', 25, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2389, 'COMP224', 'Fundamentals of Computing', 82, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8804, 'LING433', 'Fundamentals of Linguistics', 63, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5179, 'PHIL671', 'Intro Philosophy', 76, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (7146, 'SOCI282', 'Advanced Sociology', 7, 4);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2218, 'COMP787', 'Advanced Computing', 97, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (9332, 'JOUR383', 'Intro Journalism', 4, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2067, 'CHEM530', 'Advanced Chemistry', 11, 2);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8931, 'ACCO813', 'Fundamentals of Accounts', 60, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (1503, 'ECON557', 'Advanced Economics', 19, 5);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5603, 'CHEM299', 'Intro Chemistry', 42, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (5900, 'LING634', 'Advanced Linguistics', 41, 1);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (2110, 'PHIL537', 'Advanced Philosophy', 5, 3);
INSERT INTO Course (courseID, course_code, course_name, lecturerID, created_by) VALUES (8636, 'ACCO709', 'Intro Accounts', 46, 1);